verifyDepsBeforeRun: false
confirmModulesPurge: false
onlyBuiltDependencies:
  - classic-level
  - esbuild
  - msgpackr-extract
allowBuilds:
  classic-level: true
  esbuild: true
  msgpackr-extract: true
