/**
 * Equilux end-to-end on a LOCAL MIDNIGHT NETWORK.
 *
 * Deploys the compiled contract to a standalone Midnight node (docker), then
 * runs the full protocol with REAL zero-knowledge proofs generated by the
 * proof server:
 *
 *   1. deploy(employerPk)
 *   2. enroll ×4       (each produces a commitment + nullifier on-chain)
 *   3. attest ×4       (employer co-signs each commitment)
 *   4. publishReport   (proves the mean gap in-circuit, discloses only the report)
 *   5. read back latestReport from the indexer
 *
 * Prereq: docker compose -f deploy/standalone.yml up -d   (all healthy)
 * Run:    pnpm demo:standalone
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Buffer } from "node:buffer";
import { WebSocket } from "ws";
import * as Rx from "rxjs";
import * as ledgerSdk from "@midnight-ntwrk/ledger-v8";
import { unshieldedToken } from "@midnight-ntwrk/ledger-v8";
import { CompiledContract } from "@midnight-ntwrk/compact-js";
import { deployContract } from "@midnight-ntwrk/midnight-js/contracts";
import { setNetworkId, getNetworkId } from "@midnight-ntwrk/midnight-js/network-id";
import type { MidnightProvider, WalletProvider } from "@midnight-ntwrk/midnight-js/types";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import { WalletFacade } from "@midnight-ntwrk/wallet-sdk-facade";
import { DustWallet } from "@midnight-ntwrk/wallet-sdk-dust-wallet";
import { HDWallet, Roles } from "@midnight-ntwrk/wallet-sdk-hd";
import { ShieldedWallet } from "@midnight-ntwrk/wallet-sdk-shielded";
import {
  createKeystore,
  InMemoryTransactionHistoryStorage,
  PublicKey,
  UnshieldedWallet,
  type UnshieldedKeystore,
} from "@midnight-ntwrk/wallet-sdk-unshielded-wallet";
import { Contract, ledger, pureCircuits } from "../build/contract/index.js";
import {
  bytes32,
  initialPrivateState,
  padPayroll,
  witnesses,
  type EquiluxPrivateState,
} from "./witnesses.js";

// GraphQL subscriptions (wallet sync) need a global WebSocket in Node
// @ts-expect-error node global
globalThis.WebSocket = WebSocket;

setNetworkId("undeployed");

const config = {
  indexer: "http://127.0.0.1:8088/api/v3/graphql",
  indexerWS: "ws://127.0.0.1:8088/api/v3/graphql/ws",
  node: "http://127.0.0.1:9944",
  proofServer: "http://127.0.0.1:6300",
};

/** Genesis-funded dev wallet on the standalone node. */
const GENESIS_MINT_WALLET_SEED = "0000000000000000000000000000000000000000000000000000000000000001";

const EMPLOYER_SK = bytes32("acme:employer-root-secret");
const PRIVATE_STATE_ID = "equiluxPrivateState";

// 2 women (60k, 70k) + 2 men (80k, 90k) → means 65k vs 85k → gap 2352 bps
const TEAM = [
  { name: "alice", salary: 60_000n, gender: 0n, sk: bytes32("alice") },
  { name: "bob", salary: 80_000n, gender: 1n, sk: bytes32("bob") },
  { name: "carol", salary: 70_000n, gender: 0n, sk: bytes32("carol") },
  { name: "dan", salary: 90_000n, gender: 1n, sk: bytes32("dan") },
];
const CLAIMED_GAP_BPS = 2352n;

const log = (msg: string) => console.log(`[equilux] ${msg}`);
const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const short = (b: Uint8Array) => `${hex(b).slice(0, 10)}…`;

const deriveKeysFromSeed = (seed: string) => {
  const hdWallet = HDWallet.fromSeed(Buffer.from(seed, "hex"));
  if (hdWallet.type !== "seedOk") throw new Error("bad seed");
  const res = hdWallet.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  if (res.type !== "keysDerived") throw new Error("key derivation failed");
  hdWallet.hdWallet.clear();
  return res.keys;
};

async function buildWallet() {
  const keys = deriveKeysFromSeed(GENESIS_MINT_WALLET_SEED);
  const shieldedSecretKeys = ledgerSdk.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledgerSdk.DustSecretKey.fromSeed(keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], getNetworkId());

  const connection = {
    indexerClientConnection: { indexerHttpUrl: config.indexer, indexerWsUrl: config.indexerWS },
  };
  const walletConfig = {
    networkId: getNetworkId(),
    ...connection,
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, "ws")),
    txHistoryStorage: new InMemoryTransactionHistoryStorage(),
    costParameters: { additionalFeeOverhead: 300_000_000_000_000n, feeBlocksMargin: 5 },
  };
  const wallet = await WalletFacade.init({
    configuration: walletConfig as never,
    shielded: (cfg: never) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg: never) => UnshieldedWallet(cfg).startWithPublicKey(PublicKey.fromKeyStore(unshieldedKeystore)),
    dust: (cfg: never) => DustWallet(cfg).startWithSecretKey(dustSecretKey, ledgerSdk.LedgerParameters.initialParameters().dust),
  });
  await wallet.start(shieldedSecretKeys, dustSecretKey);

  log("syncing wallet with local network…");
  const synced = await Rx.firstValueFrom(wallet.state().pipe(Rx.filter((s: any) => s.isSynced)));
  const balance = synced.unshielded.balances[unshieldedToken().raw] ?? 0n;
  log(`wallet synced — unshielded balance: ${balance.toLocaleString()} NIGHT`);

  await registerForDust(wallet, unshieldedKeystore);
  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore };
}

async function registerForDust(wallet: WalletFacade, keystore: UnshieldedKeystore) {
  const state: any = await Rx.firstValueFrom(wallet.state().pipe(Rx.filter((s: any) => s.isSynced)));
  if (state.dust.availableCoins.length > 0 && state.dust.balance(new Date()) > 0n) {
    log(`dust already available: ${state.dust.balance(new Date()).toLocaleString()}`);
    return;
  }
  const utxos = state.unshielded.availableCoins.filter((c: any) => c.meta?.registeredForDustGeneration !== true);
  if (utxos.length > 0) {
    log(`registering ${utxos.length} NIGHT UTXO(s) for dust generation…`);
    const recipe = await wallet.registerNightUtxosForDustGeneration(
      utxos,
      keystore.getPublicKey(),
      (payload: Uint8Array) => keystore.signData(payload),
    );
    const finalized = await wallet.finalizeRecipe(recipe);
    await wallet.submitTransaction(finalized);
  }
  log("waiting for dust (fee token) to accrue…");
  await Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(5_000),
      Rx.filter((s: any) => s.isSynced && s.dust.balance(new Date()) > 0n),
    ),
  );
  log("dust ready");
}

/** Sign unshielded intents with the correct proof marker (wallet SDK workaround, from example-counter). */
const signTransactionIntents = (
  tx: { intents?: Map<number, any> },
  signFn: (payload: Uint8Array) => ledgerSdk.Signature,
  proofMarker: "proof" | "pre-proof",
): void => {
  if (!tx.intents || tx.intents.size === 0) return;
  for (const segment of tx.intents.keys()) {
    const intent = tx.intents.get(segment);
    if (!intent) continue;
    const cloned = ledgerSdk.Intent.deserialize<ledgerSdk.SignatureEnabled, ledgerSdk.Proofish, ledgerSdk.PreBinding>(
      "signature",
      proofMarker,
      "pre-binding",
      intent.serialize(),
    );
    const signature = signFn(cloned.signatureData(segment));
    if (cloned.fallibleUnshieldedOffer) {
      const sigs = cloned.fallibleUnshieldedOffer.inputs.map(
        (_: ledgerSdk.UtxoSpend, i: number) => cloned.fallibleUnshieldedOffer!.signatures.at(i) ?? signature,
      );
      cloned.fallibleUnshieldedOffer = cloned.fallibleUnshieldedOffer.addSignatures(sigs);
    }
    if (cloned.guaranteedUnshieldedOffer) {
      const sigs = cloned.guaranteedUnshieldedOffer.inputs.map(
        (_: ledgerSdk.UtxoSpend, i: number) => cloned.guaranteedUnshieldedOffer!.signatures.at(i) ?? signature,
      );
      cloned.guaranteedUnshieldedOffer = cloned.guaranteedUnshieldedOffer.addSignatures(sigs);
    }
    tx.intents.set(segment, cloned);
  }
};

async function makeProviders(ctx: Awaited<ReturnType<typeof buildWallet>>) {
  const state: any = await Rx.firstValueFrom(ctx.wallet.state().pipe(Rx.filter((s: any) => s.isSynced)));
  const walletAndMidnightProvider: WalletProvider & MidnightProvider = {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await ctx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: ctx.shieldedSecretKeys, dustSecretKey: ctx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      const signFn = (payload: Uint8Array) => ctx.unshieldedKeystore.signData(payload);
      signTransactionIntents(recipe.baseTransaction, signFn, "proof");
      if (recipe.balancingTransaction) signTransactionIntents(recipe.balancingTransaction, signFn, "pre-proof");
      return ctx.wallet.finalizeRecipe(recipe);
    },
    submitTx: (tx: any) => ctx.wallet.submitTransaction(tx) as any,
  };

  const currentDir = path.resolve(fileURLToPath(import.meta.url), "..");
  const zkConfigPath = path.resolve(currentDir, "..", "build");
  const zkConfigProvider = new NodeZkConfigProvider<"enroll" | "attest" | "checkReceipt" | "publishReport">(zkConfigPath);
  const accountId = walletAndMidnightProvider.getCoinPublicKey();
  const storagePassword = `${Buffer.from(accountId, "hex").toString("base64")}!`;

  return {
    privateStateProvider: levelPrivateStateProvider<typeof PRIVATE_STATE_ID>({
      privateStateStoreName: "equilux-private-state",
      accountId,
      privateStoragePasswordProvider: () => storagePassword,
    }),
    publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(config.proofServer, zkConfigProvider),
    walletProvider: walletAndMidnightProvider,
    midnightProvider: walletAndMidnightProvider,
  };
}

async function main() {
  log(`network: ${getNetworkId()} — node ${config.node}`);
  const ctx = await buildWallet();
  const providers = await makeProviders(ctx);

  const compiledContract = CompiledContract.make("equilux", Contract).pipe(
    CompiledContract.withWitnesses(witnesses),
    CompiledContract.withCompiledFileAssets(path.resolve(fileURLToPath(import.meta.url), "..", "..", "build")),
  );

  const employerPk = pureCircuits.publicKey(EMPLOYER_SK);
  log(`deploying Equilux — employerPk ${short(employerPk)}`);
  const deployed = await deployContract(providers as any, {
    compiledContract,
    args: [employerPk],
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: initialPrivateState(EMPLOYER_SK),
  } as any);
  const address = deployed.deployTxData.public.contractAddress;
  log(`deployed at ${address} (block ${deployed.deployTxData.public.blockHeight})`);

  // 1) employees enroll — each tx carries a real ZK proof
  const commitments: Uint8Array[] = [];
  for (const member of TEAM) {
    await providers.privateStateProvider.set(PRIVATE_STATE_ID, {
      ...initialPrivateState(EMPLOYER_SK),
      employeeSecret: member.sk,
      employeeRecord: [member.salary, member.gender],
    } satisfies EquiluxPrivateState);
    const res: any = await deployed.callTx.enroll();
    const cm: Uint8Array = res.private.result;
    commitments.push(cm);
    log(`enrolled ${member.name} — commitment ${short(cm)} (tx ${res.public.txId}, block ${res.public.blockHeight})`);
  }

  // 2) employer attests each commitment
  for (const [i, cm] of commitments.entries()) {
    const res: any = await deployed.callTx.attest(cm);
    log(`attested ${TEAM[i].name} (tx ${res.public.txId})`);
  }

  // 3) employer publishes the proven report
  await providers.privateStateProvider.set(PRIVATE_STATE_ID, {
    ...initialPrivateState(EMPLOYER_SK),
    payroll: padPayroll(TEAM.map((m) => ({ salary: m.salary, gender: m.gender, sk: m.sk, active: true }))),
    claimedGapBps: CLAIMED_GAP_BPS,
  } satisfies EquiluxPrivateState);
  const pub: any = await deployed.callTx.publishReport();
  log(`publishReport proven & finalized (tx ${pub.public.txId}, block ${pub.public.blockHeight})`);

  // 4) read the public ledger back from the indexer
  const contractState = await providers.publicDataProvider.queryContractState(address);
  if (!contractState) throw new Error("contract state not found via indexer");
  const l = ledger(contractState.data);
  const report = l.latestReport;
  log("──────────────────────────────────────────────");
  log(`on-chain PayReport (round ${report.value.round}):`);
  log(`  headcount   women ${report.value.headcountWomen} · men ${report.value.headcountMen}`);
  log(`  mean gap    ${(Number(report.value.meanGapBps) / 100).toFixed(2)}% (favors ${report.value.gapFavorsMen ? "men" : "women"})`);
  log(`  ≥5% joint-assessment trigger: ${report.value.meanGapAtOrAbove5pct}`);
  log(`  enrolled ${l.enrolled} · nullifiers ${l.nullifiers.size()} · attested ${l.attested.size()}`);
  log(`  salaries on chain: NONE — only commitments`);
  log("──────────────────────────────────────────────");
  log("done — every step above was proven by the local proof server");
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error(err);
    process.exit(1);
  },
);
