verifyDepsBeforeRun: false
confirmModulesPurge: false
onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
allowBuilds:
  '@swc/core': false
  msgpackr-extract: false
overrides:
  "@midnight-ntwrk/ledger-v8": 8.0.3
